package tz.co.gluhen.common.event;


public  enum AppEvent {
    USER_NEW,
    USER_UPDATE,
    NOTIFICATION_SINGLE,
    NOTIFICATION_GROUP,

    MESSAGE_NEW_CREATED,
    MESSAGE_NEW_RECEIVED,
    MESSAGE_FROM_BROWSER,
    MESSAGE_CHECK_FOR_NEW,
    MESSAGE_STOP_CHECK_FOR_NEW,
    MESSAGE_DELIVERED,
    MESSAGE_DELIVERY_FAILED,
    MESSAGE_SENT,
    MESSAGE_SENDING_FAILED,
    MESSAGE_DELIVERY_PENDING,
    FUTURE_EVENT_ADDED,
    FUTURE_EVENT_CANCELLED
}
